### ISSUE TITLE
rpush.rb File

### ISSUE THREAD

**Issue by williantenfen** [juicyparts/capistrano-rpush#1]
@melriffe  Why should we put rpush.rb from /config/initializers/  on linked_files? I think there's no sensible data on this file that will make it goes to Git-Ignore... 

And doing this I still get a info warning when deploying:
`set :rpush_conf, -> { File.join(release_path, 'config', 'initializers', 'rpush.rb') }`

Thanks!!

**Comment by melriffe** [comment]
@williantenfen The project for which I created this gem had its Rpush configuration file located in that location. Currently this gem requires the configuration file in order to issue its commands.

Please paste the warnings you are receiving.

**Comment by williantenfen** [comment]
@melriffe  This is the deploy debug: 
```
DEBUG [42034a2f] Running [ -f /home/ec2-user/quimo-staging/current/config/initializers/rpush.rb ] as ec2-user@my.ip.lal.la
DEBUG [42034a2f] Command: [ -f /home/ec2-user/quimo-staging/current/config/initializers/rpush.rb ]
DEBUG [42034a2f] Finished in 0.091 seconds with exit status 1 (failed).
WARN rpush.rb NOT FOUND!
INFO Configure rpush for your project before attempting a deployment.
```

Is this file the same from rpush configs or this is a specific file for this gem?
My rpush.rb looks like this: [rpush.rb GIST](https://gist.github.com/williantenfen/cd6af518ed0b478e34e844487c01146c)

As I can see, the Rpush gets started as a daemon process normally, but didn't noted if its working correctly yet... 

Thanks...

**Comment by melriffe** [comment]
@williantenfen Thanks for the follow-up. And thank you for sharing your rpush.rb. We are talking about the same file. Can you please let me know where, in which directory, is your rpush.rb file located?

Please look here: https://github.com/rpush/rpush/blob/master/lib/rpush/cli.rb#L12

When running ```rpush init```, the configuration file, ```rpush.rb```, appears to be created in 1 of 2 places, either as 'config/initializers/rpush.rb' or 'config/rpush.rb'.

Please try:
```set :rpush_conf, -> { File.join(release_path, 'config', 'rpush.rb') }```

or to the location of your ```rpush.rb``` configuration file.

**Comment by williantenfen** [comment]
@melriffe 
I was putting the config file on a mountable engine (rails)...
Now I made a copy of that file to my main Rails app at /config/initializers/ , too keep same place of my engine...
Now deploy is not complaining about nothing, but I'm not sure if this is the right way to handle this file (as the deploy is getting it from the current code and not from a shared folder). This is the deploy output:

```
DEBUG [340acc70] Running [ -f /home/ec2-user/quimo-staging/current/config/initializers/rpush.rb ] as ec2-user@my.ip.la.la 

DEBUG [340acc70] Command: [ -f /home/ec2-user/quimo-staging/current/config/initializers/rpush.rb ] 

DEBUG [340acc70] Finished in 0.110 seconds with exit status 0 (successful). 
```

Is this task only checking if the file exists? Or does it try to make a copy of it or something like that?
Thanks!

**Comment by melriffe** [comment]
@williantenfen Thank you for the follow-up. The gem needs the configuration file in order to issue commands to rpush. It does not make a copy of it. It does need to know where it is located, though.

Plus, the project for which I created this gem had the rpush configuration in the linked_files array. From your reply you may not need to do this.

Remove it from your linked_files array and see if the gem continues to work as expected.

**Comment by williantenfen** [comment]
@melriffe Thanks... I already don't have that file on linked_files array, and it's working as expected... 

Thank you for your time!!

**Comment by melriffe** [comment]
@williantenfen 👍 I'm glad we were able to work this out.
