### ISSUE TITLE
After upgrade to Rails5.2

### ISSUE THREAD

**Issue by kntmrkm** [juicyparts/capistrano-rpush#4]
<img width="1165" alt="1__ruby" src="https://user-images.githubusercontent.com/2703486/38874673-99df571a-4293-11e8-99a6-d6eff1e402eb.png">

I can't proceed deploy.

Any hint?

- Rails5.2
- Capistrano 3.10.2 (3.10.1 is same too)
- Rpush 3.1.1 (3.0.2 is same too)

**Comment by melriffe** [comment]
@kntmrkm I'm sorry this isn't working for you. Unfortunately I don't have any hints. However, one question: can you manually start rpush in your new rails app? If so is the command different from the one issued by this plugin?

**Comment by kntmrkm** [comment]
@melriffe thanks reply.

I tried any config, but there is no solution.

But, I can reproduce it.
Open another issue.

https://github.com/rpush/rpush/issues/430
